src/themes/victory-settings.js

`victory-settings.js` was not in sync with the latest version. This updates the font and color variables.

Bug: Update victory settings

---

package.json
src/components/footer.jsx
src/components/header.jsx
src/themes/victory.js

- Resolves https://github.com/FormidableLabs/formidable-landers/issues/2
- Add `backgroundColor` prop for both header and footer 
- Add a `max-width` style so the props name column doesn't get too wide: 
- Also converted `this.props.text` to `this.props.children` but this is a personal preference and willing to revert 
/cc @david-davidson

Task: Add backgroundColor prop to header and footer

---

src/components/footer.jsx
src/themes/victory.js

- Add `{this.props.children}` in footer.jsx
- Change to `px` units so the links look the same cross-browser
/cc @david-davidson

Task: Add support for children props in Footer 

---

package.json
src/components/footer.jsx
src/components/header.jsx

- Add `linkStyles` props to the links in `<Header />` and `<Footer />`
- Remove box shadows, background colors, and borders on the Formidable logo link
- Add `<span>` wrapper with `display: block` on `<Header />` to resolve https://github.com/FormidableLabs/formidable-landers/issues/52
- Bump version 
/cc @coopy @david-davidson

Task: Add props for overriding link styles in Header and Footer

---

package.json
src/components/footer.jsx
src/components/header.jsx

- Center text in Header
- Contrary to my previous belief, `<Header />` and `<Footer />` actually need `flex: none` to setup the page for sticky footer behavior, see https://github.com/philipwalton/solved-by-flexbox/blob/master/assets/css/components/site.css#L15-L18
/cc @david-davidson

Bug: Fix alignment in header and add setup for sticky footer

---

README.md
package.json
src/components/footer.jsx

- Add usage to `README.md`
- Since the formidable logo needs to be hosted in the project that consumes `formidable-landers`, convert the image source path to a prop so as not to restrict where it lives or its name
- Bump to version v0.0.8

Task: Add logo source path as a prop

---

src/components/footer.jsx

The `const footerLogo` was removed in favor of default props, so it’s in props now, silly! 
/cc @coopy @tptee

Bug: footer logo is undefined

---

src/themes/victory.js

Resolves https://github.com/FormidableLabs/victory/issues/182
Chose to not use the white background to help show these code blocks are **not** interactive.

Victory docs: style non-ecology code blocks

---

src/themes/victory.js

The hover state on links transitioned color too slowly (primarily for enjoyment). This cuts the transition time in half. 
/cc @david-davidson

[victory theme] Speed up transition between link colors on hover

---

.editorconfig
README.md
src/components/footer.jsx
src/components/header.jsx
src/themes/victory.js
test/.eslintrc
test/src/components/footer.spec.js
test/src/components/header.spec.js

Use the `background` shorthand in cases where we pass gradient backgrounds & radium complains about long&shorthand definitions in the same collection.
This will fix https://github.com/FormidableLabs/builder-docs/pull/24
cc @paulathevalley

Rename prop backgroundColor -> background

---

src/markdown-renderers/append-link-icon.js

Sets title to text rather than null when title is not provided

Use link name when title is blank

---

src/themes/victory.js

Once this change is published to npm, this will allow the Victory recipe playgrounds to stack vertically. See https://github.com/FormidableLabs/victory-examples/issues/28 for context.
/cc @paulathevalley, @kylecesmat 
New: 
Previous:

Update Victory theme to stack recipe playgrounds vertically

---

src/themes/victory.js

For some reason, the `counter-increment` stopped working. This fixes it. 
Bug: 
Fix: 
/cc @kylecesmat

Fix counter increment for playgrounds

---

src/markdown-renderers/ecology-playground-loading.js
src/themes/victory-settings.js
src/themes/victory.js

1. When the page has loaded, but before component playground does its thing, the code block is a tiny, unappealing textarea (Fixed byhttps://github.com/FormidableLabs/victory-examples/pull/36 )
2. When component-playground has initialized, the Figure is halfway intruding on the code block.
3. When resizing the window, glitchy things happen
https://files.slack.com/files-pri/T02913TEC-F1T67UC91/victory-recipe-doodoo.gif
1. Victory Animation example exceeding container by displaying the items as flex
2. Fixes figure intruding on codeblock by defining a sensible flex-basis and setting the SVG to a maxheight in order to contain it
3. Fixed breakpoints that caused resizing glitches to occur
4. Make default loading of components vertically-stacked
5. Add styles for dataset-select dropdown

Victory Playground Bugs

---

src/themes/victory.js

Some extra quotes snuck into the `content` attribute.
/cc @kylecesmat @bmathews

Bug: Remove extra quotes

---

src/themes/victory.js

Adding styles for the buttons to export to gist & save to clipboard. The links are outlines that become solid when hovered.
Will need to add the props to the various victory repositories.
Closes https://github.com/FormidableLabs/victory-docs/issues/29

Style gist/clipboard buttons

---

src/themes/victory.js

This PR will:
- Add spacing between playground rendered components that contain dropdowns
- Fix the mobile breakpoint issue present at 650px
cc @paulathevalley @bmathews 
Before:
After:

Fix Dropdown Spacing, Mobile Playground Issues

---

demo/index.html
src/components/footer.jsx
src/components/header.jsx

- Fix typo in font name (should be akkurat not akkurta) 
- Upload minified fonts.css with font families: `"akkurat"`, `"sharp"`, and `"tiempos"` (Resolves first part of https://github.com/FormidableLabs/formidable-landers/issues/162)
/cc @kylecesmat

Fix typo in font name

---

src/components/footer.jsx
src/components/header.jsx

Fix bug where logo in header was exceeding the width of narrow screen sizes. 
screenshot:

Fix logo overflow on header on narrow screen sizes

---

demo/demo.js
src/components/footer.jsx
src/components/header.jsx
test/src/components/footer.spec.js
test/src/components/header.spec.js

- Allow `this.props.style` to override all other styles
- Add a `.container` wrapper of the content, so the dox can adjust its styles to match the layout/container of the page
/cc @kylecesmat

Fix style ordering, add container wrapper

---

src/components/footer.jsx
src/components/header.jsx

- Add a logo class to target the styles—particularly useful for centering both logo and links with media queries 
- Change `marginRight` to `margin` in the header so it matchs the API in footer

Add classname to target logo styles

---

src/themes/victory.js

Resolves https://github.com/FormidableLabs/victory-docs/issues/124
before:
after:
thanks to the simple brilliance of @bmathews

Do not show scrollbars by default

---

src/themes/victory-settings.js
src/themes/victory.js

- Add `.playgroundsMaxHeight` class back to restrict playground height 
- Desaturate colors so there’s less clashing with the space-branded `<Header />`
- Opted to replace the monospace font on Google Fonts with our very own akkurat

Update Victory Stylesheet

---

demo/demo.css
demo/demo.js
src/components/header.js

On the lander demo, if you don't include the sub-header, the page needed extra space to make up for how the formidable.com header overlaps the content. In practice on the formidable.com page, however, the extra space is not necessary. 
I have removed the extra 3em, and added some styling on the demo to better match how the page functions without the sub-header. 
Before image:
After fix:

Fix extra spacing above header on Formidable.com

---

src/partials/formidable-header.js
test/src/components/header.spec.js

Update header to close mobile sized menu when window is resized to desktop width.
closes https://github.com/FormidableLabs/formidable.com/issues/457

Fix resize issue with menu

---

package.json

Move react-side-effect from a dev dependency to a dependency for use with builder scripts

Move react-side-effect dependency

---

package-lock.json
package.json
src/components/footer.js
src/components/header.js

This PR adds the `prop-types` package rather than relying on `React.PropTypes`

use prop-types for react 16+ compat

---

.gitignore
src/components/header.js
src/partials/formidable-header.js
src/partials/nav-link.js

The assumption that we will always use anchor tags with SSR is no longer true, nor do we want to assume a one-size-fits all approach for what the activeLink logic will be, so we're providing the previous hardcoding as the sensible default: ``` props => props.current === props.item.path``` while still allowing configuration. 
Additionally, by default we want to skip a full page reload when the current path is selected again, but we _also_ don't want to make that behavior impossible since that would be swapping out one set of present assumptions for another set of present assumptions, and the future remains clouded in mystery.
This is meant to meet an immediate need for the new formidable.com, in the long run exporting configurable partials and allowing for full per-project …

Link configuration props
