FormidableLabs/formidable-landers

src/components/header.jsx

This one's a merge-right-away: I need configurable header text to unblock tweaks to the Victory site for tonight's meetup! (We can come back and add the footer later.)
/cc @coopy @paulathevalley

Make text configurable

---

.babelrc
.gitignore
.npmignore
package.json
src/assets/logos.jsx
src/components/footer.jsx
src/components/header.jsx
src/index.js
src/themes/victory-settings.js
test/src/components/footer.spec.js
test/src/components/header.spec.js
webpack.config.test.js

Support babel6

---

src/themes/victory-settings.js
src/themes/victory.js

Adjusted colors, spacing and added a new breakpoint for victory.

Task: Adjust settings for /docs page

---

src/themes/victory.js

This plays nicely with the responsive SVGs!

Update victory theme for responsive SVGs

---

src/components/footer.jsx
src/components/header.jsx
test/src/components/footer.spec.js
test/src/components/header.spec.js

- Update link to careers page 
- Change header copy

Update header copy

---

src/themes/victory-settings.js
src/themes/victory.js

- Adjust look of component playground as per @eastridge request 
- Upgrade ecology for better codemirror theme support
- Add 😎 CodeMirror theme 
- Restrict height of playground on homepage 
- Speed up hover transition 
/cc @boygirl

Task: Restyle playground for Victory

---

src/themes/victory-settings.js
src/themes/victory.js

Resolves https://github.com/FormidableLabs/victory-docs/issues/35
- Remove unused classes 
- Add focus state to playgrounds 
- Adjust error state so it's more readable

Task: Polish playgrounds 

---

src/assets/logo-formidable-black.svg

As of React v15.2.0 - unused DOM properties trigger an error message in the console
cc @coopy @paulathevalley

Remove xmlns property

---

src/index.js
src/markdown-renderers/append-link-icon.js
src/markdown-renderers/external-link-icons.js
src/markdown-renderers/icon-external.svg
src/markdown-renderers/icon-internal.svg

Add a shared custom ecology renderer method that appends icons to links depending on if they are internal or external to formidable labs.
cc @coopy

Add function for internal/external link

---

src/index.js
src/markdown-renderers/ecology-playground-loading.js

This renderer will return placeholder DOM elements for use in victory-docs and other places where an ecology playground is server-side rendered
cc @paulathevalley

Add renderer for ecology playground loading

---

README.md

Adding the new domains & updating content about builder.
cc @paulathevalley

Update readme project links

---

src/themes/victory-settings.js
src/themes/victory.js

Supporting stylesheet for https://github.com/FormidableLabs/victory-docs/pull/81

VictoryTheme: Adjust headings, spacing, and link colors

---

src/themes/victory.js

cc @paulathevalley @kylecesmat

make recipes bigger

---

.gitignore
demo/demo.js
demo/index.html
demo/webpack.config.dev.js
package.json

Resolves https://github.com/FormidableLabs/formidable-landers/issues/78
- Add a basic demo page that displays the default `<Header />` and `<Footer />` components
/cc @chrisbolin

Feature: Add demo page

---

package.json
postcss.config.js

This PR fixes two errors when running `npm test` due to minor package updates.

Fix two errors in test

---

package.json

chore(package): update postcss-import to version 10.0.0

---

package.json

chore(package): update normalize.css to version 7.0.0

---

package.json

chore(package): update webpack-dashboard to version 1.0.0-5

---

package.json

chore(package): update eslint-plugin-react to version 7.3.0

---

.travis.yml

Update node matrix on travis

---

README.md
demo/demo.js
src/components/cookie-banner.js
src/components/header.js
src/index.js
src/styles/cookie-banner.css
test/src/components/header.spec.js

This PR: 
* Add a `CookieBanner` component to the `Header` component so it appears first in the DOM for best accessibility.

Add cookie banner
